name: Deploy Cloud Functions
on:
  push:
    branches:
      - "main"
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: "auth"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

    - id: "deploy1"
      uses: "google-github-actions/deploy-cloud-functions@v0"
      with:
        name: "function-1"
        runtime: "python310"
        source_dir: gcp-crud-api/get-user
        region: asia-northeast1
        description: crud trigger
        entry_point: get_user
        ingress_settings: ALLOW_ALL
        
    
    - id: "deploy2"
      uses: "google-github-actions/deploy-cloud-functions@v0"
      with:
        name: "function-2"
        runtime: "python310"
        source_dir: gcp-crud-api/create-user
        region: asia-northeast1
        description: crud trigger
        entry_point: create_data
        ingress_settings: ALLOW_ALL
        
    - id: "deploy3"
      uses: "google-github-actions/deploy-cloud-functions@v0"
      with:
        name: "function-3"
        runtime: "python310"
        source_dir: gcp-crud-api/update-user
        region: asia-northeast1
        description: crud trigger
        entry_point: update_data
        ingress_settings: ALLOW_ALL
      
    - id: "deploy4"
      uses: "google-github-actions/deploy-cloud-functions@v0"
      with:
        name: "function-4"
        runtime: "python310"
        source_dir: gcp-crud-api/delete-user
        region: asia-northeast1
        description: crud trigger
        entry_point: delete_data
        ingress_settings: ALLOW_ALL
